#driverClassName=org.sqlite.JDBC
#url=jdbc:sqlite:memory:test?cache=shared
#url=jdbc:sqlite:test.db
#username=sa
#password=sa
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#hibernate.hbm2ddl.auto=create
#hibernate.show_sql=true
#server.port=8080

spring:
  datasource:
    url: jdbc:h2:mem:~/demoApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true